apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.129.0.9:6443
    token: <generated-token>
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: <generated-token>
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 10.129.0.102
    bindPort: 6443
  certificateKey: <generated-control-plane-certificate-key>
nodeRegistration:
  criSocket: unix:///run/cri-dockerd.sock
  imagePullPolicy: IfNotPresent
  name: k8s-mas-1..3 #replace with actual master node name eg k8s-mas-2
  taints: null